services:
  - type: web
    name: virtud-y-victoria-277
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /wp-login.php
    envVars:
      - key: WORDPRESS_DB_HOST
        fromService:
          type: pserv
          name: virtud-db
          property: host
      - key: WORDPRESS_DB_NAME
        value: virtud_y_victoria
      - key: WORDPRESS_TABLE_PREFIX
        value: wp_
      - key: WORDPRESS_DEBUG
        value: "false"
      - key: WORDPRESS_CONFIG_EXTRA
        value: "define('WP_HOME','https://virtud-y-victoria-277.onrender.com'); define('WP_SITEURL','https://virtud-y-victoria-277.onrender.com'); define('WP_ENVIRONMENT_TYPE', 'production');"
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: virtud-db
          property: connectionString

  - type: pserv
    name: virtud-db
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.mariadb
    dockerContext: .
    envVars:
      - key: MYSQL_DATABASE
        value: virtud_y_victoria
      - key: MYSQL_USER
        value: virtud_user
      - key: MYSQL_PASSWORD
        value: virtud_pass
      - key: MYSQL_ROOT_PASSWORD
        value: root_pass
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 1